server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: toor
    url: jdbc:postgresql://localhost:5432/backend
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop